#!/bin/bash
echo "Updating Your System"
sudo apt update
echo "Installing the required packages in order for the script to work properly"
sudo  apt install -y wget novnc websockify tigervnc-standalone-server tar
cd ~/
wget https://cdn1.waterfox.net/waterfox/releases/6.5.3/Linux_x86_64/waterfox-6.5.3.tar.bz2 && sudo tar -xf waterfox-6.5.3.tar.bz2
git clone https://github.com/gitxpresso/linux-novnc.git
vncserver -SecurityTypes none  --I-KNOW-THIS-IS-INSECURE  -localhost no :0
websockify -D --web=/usr/share/novnc/ --cert=~/linux-novnc/novnc.pem 6080 localhost:5900
ssh -L 5900:localhost:5900 192.168.86.5 "x11vnc -create -env FD_PROG=~/waterfox/waterfox -nopw -listen 127.0.0.1 -forever"
